name: microblog
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fpdart: ^1.1.1
  supabase_flutter: ^2.8.4
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  uuid: ^4.5.1
  intl: ^0.20.2
  internet_connection_checker_plus: ^2.7.1
  hive: ^2.2.3
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"

flutter:
  uses-material-design: true
